// flow-typed signature: 03c617605f9796a5c34573ae9d991ce5
// flow-typed version: <<STUB>>/babel-plugin-i18next-extract_v^0.6.1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-i18next-extract'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-i18next-extract' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-i18next-extract/lib/index.es' {
  declare module.exports: any;
}

declare module 'babel-plugin-i18next-extract/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-i18next-extract/lib/index.es.js' {
  declare module.exports: $Exports<'babel-plugin-i18next-extract/lib/index.es'>;
}
declare module 'babel-plugin-i18next-extract/lib/index' {
  declare module.exports: $Exports<'babel-plugin-i18next-extract/lib'>;
}
declare module 'babel-plugin-i18next-extract/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-i18next-extract/lib'>;
}
