// flow-typed signature: 0301aa6306be4b395e224e5cf6080c54
// flow-typed version: <<STUB>>/docz-theme-default_v^1.2.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docz-theme-default'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docz-theme-default' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docz-theme-default/dist/chunk.esm' {
  declare module.exports: any;
}

declare module 'docz-theme-default/dist/chunk' {
  declare module.exports: any;
}

declare module 'docz-theme-default/dist/index.esm' {
  declare module.exports: any;
}

declare module 'docz-theme-default/dist/index.esm2' {
  declare module.exports: any;
}

declare module 'docz-theme-default/dist' {
  declare module.exports: any;
}

declare module 'docz-theme-default/dist/index2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docz-theme-default/dist/chunk.esm.js' {
  declare module.exports: $Exports<'docz-theme-default/dist/chunk.esm'>;
}
declare module 'docz-theme-default/dist/chunk.js' {
  declare module.exports: $Exports<'docz-theme-default/dist/chunk'>;
}
declare module 'docz-theme-default/dist/index.esm.js' {
  declare module.exports: $Exports<'docz-theme-default/dist/index.esm'>;
}
declare module 'docz-theme-default/dist/index.esm2.js' {
  declare module.exports: $Exports<'docz-theme-default/dist/index.esm2'>;
}
declare module 'docz-theme-default/dist/index' {
  declare module.exports: $Exports<'docz-theme-default/dist'>;
}
declare module 'docz-theme-default/dist/index.js' {
  declare module.exports: $Exports<'docz-theme-default/dist'>;
}
declare module 'docz-theme-default/dist/index2.js' {
  declare module.exports: $Exports<'docz-theme-default/dist/index2'>;
}
