// flow-typed signature: 181948db6bdebd4fb05910c8c9161663
// flow-typed version: <<STUB>>/eslint-plugin-react-app_v^6.2.1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-react-app/src/config' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-app/src' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-app/src/plugins' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-react-app/src/config.js' {
  declare module.exports: $Exports<'eslint-plugin-react-app/src/config'>;
}
declare module 'eslint-plugin-react-app/src/index' {
  declare module.exports: $Exports<'eslint-plugin-react-app/src'>;
}
declare module 'eslint-plugin-react-app/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-react-app/src'>;
}
declare module 'eslint-plugin-react-app/src/plugins.js' {
  declare module.exports: $Exports<'eslint-plugin-react-app/src/plugins'>;
}
