// flow-typed signature: cdca6226aa70c223f83c6e1645de2331
// flow-typed version: <<STUB>>/postcss-color-mod-function_v^3.0.3/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-color-mod-function'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-color-mod-function' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-color-mod-function/index.cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-color-mod-function/index.cjs.js' {
  declare module.exports: $Exports<'postcss-color-mod-function/index.cjs'>;
}
