// flow-typed signature: 5a074674f9876af831dbec43d82d560e
// flow-typed version: <<STUB>>/postcss-font-smoothing_v^0.1.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-font-smoothing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-font-smoothing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-font-smoothing/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-font-smoothing/index' {
  declare module.exports: $Exports<'postcss-font-smoothing'>;
}
declare module 'postcss-font-smoothing/index.js' {
  declare module.exports: $Exports<'postcss-font-smoothing'>;
}
declare module 'postcss-font-smoothing/test/index' {
  declare module.exports: $Exports<'postcss-font-smoothing/test'>;
}
declare module 'postcss-font-smoothing/test/index.js' {
  declare module.exports: $Exports<'postcss-font-smoothing/test'>;
}
