// flow-typed signature: f2ba43e442feb97f9d2e685416c95801
// flow-typed version: <<STUB>>/postcss-partial-import_v^4.1.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-partial-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-partial-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-partial-import/lib/escape-reg-exp' {
  declare module.exports: any;
}

declare module 'postcss-partial-import/lib/mkdir' {
  declare module.exports: any;
}

declare module 'postcss-partial-import/lib/path-contains-path' {
  declare module.exports: any;
}

declare module 'postcss-partial-import/lib/resolve-id' {
  declare module.exports: any;
}

declare module 'postcss-partial-import/lib/touch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-partial-import/index' {
  declare module.exports: $Exports<'postcss-partial-import'>;
}
declare module 'postcss-partial-import/index.js' {
  declare module.exports: $Exports<'postcss-partial-import'>;
}
declare module 'postcss-partial-import/lib/escape-reg-exp.js' {
  declare module.exports: $Exports<'postcss-partial-import/lib/escape-reg-exp'>;
}
declare module 'postcss-partial-import/lib/mkdir.js' {
  declare module.exports: $Exports<'postcss-partial-import/lib/mkdir'>;
}
declare module 'postcss-partial-import/lib/path-contains-path.js' {
  declare module.exports: $Exports<'postcss-partial-import/lib/path-contains-path'>;
}
declare module 'postcss-partial-import/lib/resolve-id.js' {
  declare module.exports: $Exports<'postcss-partial-import/lib/resolve-id'>;
}
declare module 'postcss-partial-import/lib/touch.js' {
  declare module.exports: $Exports<'postcss-partial-import/lib/touch'>;
}
