// flow-typed signature: 2839db955840faa177a36c3c6a769146
// flow-typed version: <<STUB>>/postcss-normalize_v^8.0.1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-normalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-normalize/index.cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-normalize/index.cjs.js' {
  declare module.exports: $Exports<'postcss-normalize/index.cjs'>;
}
