// flow-typed signature: 8399426eb80be1126dc3d576122b36e3
// flow-typed version: <<STUB>>/typy_v^3.3.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typy/lib' {
  declare module.exports: any;
}

declare module 'typy/lib/typy' {
  declare module.exports: any;
}

declare module 'typy/lib/util' {
  declare module.exports: any;
}

declare module 'typy/src' {
  declare module.exports: any;
}

declare module 'typy/src/typy' {
  declare module.exports: any;
}

declare module 'typy/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typy/lib/index' {
  declare module.exports: $Exports<'typy/lib'>;
}
declare module 'typy/lib/index.js' {
  declare module.exports: $Exports<'typy/lib'>;
}
declare module 'typy/lib/typy.js' {
  declare module.exports: $Exports<'typy/lib/typy'>;
}
declare module 'typy/lib/util.js' {
  declare module.exports: $Exports<'typy/lib/util'>;
}
declare module 'typy/src/index' {
  declare module.exports: $Exports<'typy/src'>;
}
declare module 'typy/src/index.js' {
  declare module.exports: $Exports<'typy/src'>;
}
declare module 'typy/src/typy.js' {
  declare module.exports: $Exports<'typy/src/typy'>;
}
declare module 'typy/src/util.js' {
  declare module.exports: $Exports<'typy/src/util'>;
}
